**Import numpy as np and print the version number.**

In [22]:
import numpy as np
print(np.__version__)

1.24.3


 **Create a 1D array of numbers from 0 to 9**

In [30]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Create a 3×3 numpy array of all True’s**

In [35]:
boolArr = np.full((3,3), True, dtype=bool)
print(boolArr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Extract all odd numbers from arr**

In [44]:
oddArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

oddArr[oddArr % 2 == 1]

array([1, 3, 5, 7, 9])

**Replace all odd numbers in arr with -1**

In [49]:
oddArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
oddArr[oddArr % 2 == 1] = -1
print(oddArr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Replace all odd numbers in arr with -1 without changing arr**

In [51]:
oddArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
oddArrCopy = oddArr.copy()
oddArrCopy[oddArrCopy % 2 == 1] = -1
print(oddArr)
print(oddArrCopy)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Convert a 1D array to a 2D array with 2 rows**

In [55]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])